apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docpilot

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - qdrant.yaml
  - postgres.yaml
  - redis.yaml
  - mlflow.yaml
  - prometheus.yaml
  - grafana.yaml
  - ingress.yaml